name: lar__cia
description: "Explore e encontre o lar dos seus sonhos ou o imóvel ideal para investir com Hebert Paes, seu portal imobiliário moderno e responsivo, adaptável ao seu estilo com tema claro ou escuro."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_storage: ^13.0.0
  geolocator: 13.0.4
  fl_chart: 0.68.0
  firebase_analytics: ^12.0.0
  cloud_functions: ^6.0.0
  flutter_stripe: ^12.0.0
  encrypt: ^5.0.0
  cloud_firestore: '>=5.5.0'
  firebase_auth: '>=5.3.3'
  firebase_core: ^4.2.0
  flutter_svg: ^2.0.0
  file_picker: '>=8.1.2'
  latlong2: 0.9.1
  flutter_map: ^8.0.0
  http: ^1.0.0
  url_launcher: ^6.0.0
  intl: 0.20.2
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
