-- Gerado por generate-seed.mjs — NÃO editar à mão.
USE lar_cia;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE financing_documents;
TRUNCATE TABLE financing_applications;
TRUNCATE TABLE schedule_events;
TRUNCATE TABLE property_reviews;
TRUNCATE TABLE favorites;
TRUNCATE TABLE property_proximities;
TRUNCATE TABLE property_images;
TRUNCATE TABLE blog_post_tags;
TRUNCATE TABLE blog_posts;
TRUNCATE TABLE leads;
TRUNCATE TABLE newsletter_subscriptions;
TRUNCATE TABLE properties;
TRUNCATE TABLE categories;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO categories (id,name,icon,sort_order) VALUES ('casa','Casas','home',0);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('apartamento','Apartamentos','apartment',1);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('praia','Beira-mar','beach',2);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('piscina','Com piscina','pool',3);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('luxo','Alto padrão','diamond',4);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('condominio','Condomínio','gate',5);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('rural','Rural','tree',6);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('florais_da_mata','Florais da Mata','leaf',7);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('sitios_chacaras','Sítios e chácaras','barn',8);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('cuiaba','Cuiabá','city',9);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('fazenda','Fazendas','cow',10);
INSERT INTO categories (id,name,icon,sort_order) VALUES ('exotico','Exóticos','palm',11);

INSERT INTO users (id,name,email,avatar_url,is_admin,approved,access_level,perm_manage_sites,perm_manage_panels,perm_approve_users,perm_manage_ads,perm_manage_financing,preferred_category,phone_number,whatsapp_opt_in,credit_analysis_consent,data_sharing_consent) VALUES ('admin_user_001','Hebert Paes','ciencia@msn.com','https://i.pravatar.cc/150?u=ciencia@msn.com',1,1,3,1,1,1,1,1,'luxo','+5565999887766',1,1,1);

INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_001','Casa térrea em condomínio fechado','Florais da Mata, Várzea Grande - MT',1290000,4,5,4,3,'florais_da_mata','Casa de alto padrão em condomínio com segurança 24h, área gourmet, piscina aquecida e acabamento premium. Próximo a escolas e ao shopping.',380,'sale',1,2021,980,-15.6571,-56.1325,1,0.96,'manual','2024-05-20 00:00:00','2024-06-20 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_001','https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_001','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_001','Shopping');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_001','Escolas');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_001','Parque');
INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_002','Apartamento alto padrão com vista para o Rio Cuiabá','Jardim Aclimação, Cuiabá - MT',890000,3,3,2,2,'apartamento','Apartamento com 3 suítes, varanda gourmet integrada e lazer completo no condomínio. Andar alto, sol da manhã.',142,'sale',1,2020,720,-15.5989,-56.0949,1,0.9,'ai','2024-05-15 00:00:00','2024-06-18 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_002','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_002','https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_002','Orla');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_002','Restaurantes');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_002','Academia');
INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_003','Cobertura duplex de luxo com piscina privativa','Bosque da Saúde, Cuiabá - MT',2450000,4,6,4,4,'luxo','Cobertura duplex com piscina privativa, espaço gourmet, home theater e acabamentos importados. Vista panorâmica da cidade.',410,'sale',1,2022,1450,-15.5783,-56.0892,1,0.98,'manual','2024-04-25 00:00:00','2024-06-16 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_003','https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_003','https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_003','Centro');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_003','Hospital');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_003','Shopping');
INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_004','Apartamento 2 quartos para alugar mobiliado','Goiabeiras, Cuiabá - MT',2800,2,2,1,1,'apartamento','Totalmente mobiliado e decorado, pronto para morar. Condomínio com piscina, academia e portaria 24h.',68,'monthly',1,2019,540,-15.6097,-56.0674,1,0.85,'ai','2024-05-31 00:00:00','2024-06-20 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_004','https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_004','https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_004','UFMT');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_004','Shopping Goiabeiras');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_004','Av. Fernando Corrêa');
INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_005','Chácara com lago e pomar a 20 min de Cuiabá','Zona Rural, Santo Antônio de Leverger - MT',750000,3,2,6,1,'sitios_chacaras','Chácara com sede de 3 quartos, lago para pesca, pomar e área de churrasqueira. Ideal para descanso ou renda com eventos.',5000,'sale',1,2015,0,-15.8669,-56.0764,0,0.6,'','2024-04-18 00:00:00','2024-06-14 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_005','https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_005','https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_005','Rio Cuiabá');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_005','Balneário');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_005','Estrada asfaltada');
INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_006','Fazenda produtiva 1.200 hectares com pecuária','Rosário Oeste - MT',18500000,5,4,10,2,'fazenda','Fazenda dupla aptidão com 1.200 ha, pastagens formadas, curral, sede e dois funcionários. Documentação regular e georreferenciada.',12000000,'sale',1,2010,0,-14.8333,-56.4167,1,0.93,'manual','2024-03-31 00:00:00','2024-06-12 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_006','https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_006','https://images.unsplash.com/photo-1444858345149-8ff5f0fa7a3a?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_006','BR-364');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_006','Cidade 35km');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_006','Energia trifásica');
INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_007','Casa de campo com piscina em condomínio de chácaras','Acorizal - MT',3500,3,3,4,1,'piscina','Casa de temporada com piscina, churrasqueira, Wi-Fi e capacidade para 12 pessoas. Diária com café incluso.',800,'daily',1,2018,0,-15.2,-56.3667,1,0.88,'ai','2024-05-24 00:00:00','2024-06-19 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_007','https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_007','https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_007','Cachoeira');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_007','Trilhas');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_007','Pesque-pague');
INSERT INTO properties (id,title,location,price,bedrooms,bathrooms,garages,suites,category,description,area,rental_type,is_active,year_built,condo_fee,latitude,longitude,is_verified,verification_score,verified_by,created_at,updated_at) VALUES ('prop_008','Sobrado moderno em condomínio com lazer completo','Ribeirão do Lipa, Cuiabá - MT',1150000,4,4,3,2,'condominio','Sobrado com arquitetura contemporânea, pé-direito duplo, automação residencial e energia solar. Condomínio com clube.',260,'sale',1,2023,650,-15.5556,-56.0722,1,0.94,'manual','2024-06-04 00:00:00','2024-06-20 00:00:00');
INSERT INTO property_images (property_id,url,position) VALUES ('prop_008','https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',0);
INSERT INTO property_images (property_id,url,position) VALUES ('prop_008','https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=1200&q=80',1);
INSERT INTO property_proximities (property_id,label) VALUES ('prop_008','UFMT');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_008','Shopping');
INSERT INTO property_proximities (property_id,label) VALUES ('prop_008','Saída para Chapada');

INSERT INTO blog_posts (id,slug,title,subtitle,excerpt,body,hero_image_url,author_name,is_featured,priority,published_at,updated_at) VALUES ('post_001','financiamento-imovel-cuiaba-2026','Como financiar seu imóvel em Cuiabá em 2026: guia completo','Taxas, bancos e documentos sem complicação','Entenda as linhas de crédito, simule parcelas e descubra como aprovar seu financiamento mais rápido na região metropolitana de Cuiabá.','O financiamento imobiliário continua sendo o principal caminho para a casa própria...','https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80','Hebert Paes',1,10,'2024-06-14 00:00:00','2024-06-14 00:00:00');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_001','financiamento');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_001','investimento');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_001','cuiaba');
INSERT INTO blog_posts (id,slug,title,subtitle,excerpt,body,hero_image_url,author_name,is_featured,priority,published_at,updated_at) VALUES ('post_002','florais-da-mata-vale-a-pena','Morar no Florais da Mata vale a pena? Veja prós e contras','O bairro planejado de Várzea Grande sob análise','Segurança, valorização e infraestrutura: analisamos se o Florais da Mata é o melhor investimento para a sua família em 2026.','O Florais da Mata se consolidou como um dos endereços mais desejados...','https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80','Hebert Paes',1,8,'2024-06-07 00:00:00','2024-06-07 00:00:00');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_002','bairros');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_002','investimento');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_002','florais_da_mata');
INSERT INTO blog_posts (id,slug,title,subtitle,excerpt,body,hero_image_url,author_name,is_featured,priority,published_at,updated_at) VALUES ('post_003','investir-em-fazendas-mato-grosso','Investir em fazendas em Mato Grosso: rentabilidade e cuidados','O agro como ativo de longo prazo','Mato Grosso lidera a produção agropecuária do país. Veja como avaliar uma fazenda e os documentos essenciais antes de comprar.','A aquisição de terras produtivas exige análise de georreferenciamento...','https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1200&q=80','Hebert Paes',0,5,'2024-05-24 00:00:00','2024-05-24 00:00:00');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_003','agro');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_003','fazenda');
INSERT INTO blog_post_tags (post_id,tag) VALUES ('post_003','investimento');

INSERT INTO property_reviews (id,property_id,author_name,rating,comment,created_at) VALUES ('rev_001','prop_003','Marina T.',5,'Atendimento impecável do Hebert. Cobertura ainda melhor pessoalmente!','2024-06-12 00:00:00');
INSERT INTO property_reviews (id,property_id,author_name,rating,comment,created_at) VALUES ('rev_002','prop_001','Carlos E.',5,'Processo de compra muito transparente e rápido.','2024-06-10 00:00:00');
INSERT INTO property_reviews (id,property_id,author_name,rating,comment,created_at) VALUES ('rev_003','prop_002','Júlia R.',4,'Vista incrível, recomendo visitar no fim da tarde.','2024-06-08 00:00:00');
